2024-11-08 09:30:53,502 INFO: Microblog startup [in C:\Users\Wiktor\microblog\app\__init__.py:43]
2024-11-08 09:39:14,153 INFO: Microblog startup [in C:\Users\Wiktor\microblog\app\__init__.py:43]
2024-11-08 09:40:34,694 INFO: Microblog startup [in C:\Users\Wiktor\microblog\app\__init__.py:43]
2024-11-08 09:45:16,089 INFO: Microblog startup [in C:\Users\Wiktor\microblog\app\__init__.py:43]
2024-11-08 10:04:22,366 INFO: Microblog startup [in C:\Users\Wiktor\microblog\app\__init__.py:43]
2024-11-08 10:04:42,687 ERROR: Exception on /index [GET] [in C:\Users\Wiktor\microblog\venv\Lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Users\Wiktor\microblog\venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wiktor\microblog\venv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wiktor\microblog\venv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wiktor\microblog\venv\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Wiktor\microblog\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Wiktor\microblog\app\routes.py", line 23, in index
    form = PostForm()
  File "C:\Users\Wiktor\microblog\venv\Lib\site-packages\wtforms\form.py", line 209, in __call__
    return type.__call__(cls, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
TypeError: PostForm.__init__() missing 1 required positional argument: 'original_username'
2024-11-08 10:05:04,362 ERROR: Exception on /index [GET] [in C:\Users\Wiktor\microblog\venv\Lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Users\Wiktor\microblog\venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wiktor\microblog\venv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wiktor\microblog\venv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wiktor\microblog\venv\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Wiktor\microblog\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Wiktor\microblog\app\routes.py", line 23, in index
    form = PostForm()
  File "C:\Users\Wiktor\microblog\venv\Lib\site-packages\wtforms\form.py", line 209, in __call__
    return type.__call__(cls, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
TypeError: PostForm.__init__() missing 1 required positional argument: 'original_username'
2024-11-08 10:05:06,767 ERROR: Exception on /index [GET] [in C:\Users\Wiktor\microblog\venv\Lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Users\Wiktor\microblog\venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wiktor\microblog\venv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wiktor\microblog\venv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wiktor\microblog\venv\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Wiktor\microblog\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Wiktor\microblog\app\routes.py", line 23, in index
    form = PostForm()
  File "C:\Users\Wiktor\microblog\venv\Lib\site-packages\wtforms\form.py", line 209, in __call__
    return type.__call__(cls, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
TypeError: PostForm.__init__() missing 1 required positional argument: 'original_username'
2024-11-08 10:05:15,745 ERROR: Exception on /index [GET] [in C:\Users\Wiktor\microblog\venv\Lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Users\Wiktor\microblog\venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wiktor\microblog\venv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wiktor\microblog\venv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wiktor\microblog\venv\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Wiktor\microblog\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Wiktor\microblog\app\routes.py", line 23, in index
    form = PostForm()
  File "C:\Users\Wiktor\microblog\venv\Lib\site-packages\wtforms\form.py", line 209, in __call__
    return type.__call__(cls, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
TypeError: PostForm.__init__() missing 1 required positional argument: 'original_username'
2024-11-08 10:05:17,832 ERROR: Exception on /index [GET] [in C:\Users\Wiktor\microblog\venv\Lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Users\Wiktor\microblog\venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wiktor\microblog\venv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wiktor\microblog\venv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wiktor\microblog\venv\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Wiktor\microblog\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Wiktor\microblog\app\routes.py", line 23, in index
    form = PostForm()
  File "C:\Users\Wiktor\microblog\venv\Lib\site-packages\wtforms\form.py", line 209, in __call__
    return type.__call__(cls, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
TypeError: PostForm.__init__() missing 1 required positional argument: 'original_username'
2024-11-08 10:05:19,372 ERROR: Exception on /user/aaa [GET] [in C:\Users\Wiktor\microblog\venv\Lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Users\Wiktor\microblog\venv\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Wiktor\microblog\venv\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Wiktor\microblog\venv\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Wiktor\microblog\venv\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Wiktor\microblog\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Wiktor\microblog\app\routes.py", line 104, in user
    per_page=app.config['POSTS_PER_PAGE'],
             ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'POSTS_PER_PAGE'
2024-11-08 10:06:34,361 INFO: Microblog startup [in C:\Users\Wiktor\microblog\app\__init__.py:43]
